### ISSUE TITLE
libensemble osx-arm64 build

### ISSUE THREAD

**Issue by berceanu** [conda-forge/libensemble-feedstock#34]
### Comment:

Are there plans for an osx-arm64 build for the newer Apple Sillicon-based macs? 
I am willing to test/assist if necessary.

**Comment by shuds13** [comment]
We should be supporting this. I am guessing it can just be added to conda-forge.yml to create the build.

**Comment by jlnav** [comment]
Hi @berceanu , osx-arm64 is locally well-tested via my macbook, though I agree an additional corresponding CI build would be very helpful.

**Comment by berceanu** [comment]
Awesome!
